export const AVISOS = 'vult/avisos'
export const CONFINAMENTOS = 'vult/confinamentos'
export const HOME = 'vult/'
export const INSEMINACOES = 'vult/inseminacoes'
export const MATRIZES = 'vult/matrizes'
export const PARAMETROS = 'vult/parametros'
export const PLANOS = 'vult/planos'
export const REGISTROS = 'vult/registros'
